webApp/beewatch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.conf.urls.i18n import i18n_patterns
from django_registration.backends.one_step.views import RegistrationView
from main.forms import UserRegistrationForm

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('annotations/', include('main.urls.annotation_urls')),
    path('api/', include('main.urls.api.urls'))
]

urlpatterns += i18n_patterns(
    path('', include('main.urls.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('accounts/register/',
         RegistrationView.as_view(form_class=UserRegistrationForm),
         name='django_registration_register'),
    path('accounts/',
         include('django_registration.backends.activation.urls')),
    path('admin/', admin.site.urls),

    path('beefoodchecker/', include(
        'main.urls.environment.beefoodchecker_urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webApp/main/urls/api/urls.py
from django.urls import path, include

urlpatterns = [
    path('images/', include('main.urls.api.image_urls')),
    path('plants/', include('main.urls.api.plant_urls'))
]

webApp/main/urls/urls.py
from django.urls import path, include

from main.views import views, beehive_views, video_views, apiary_views, \
    frame_views, annotation_views, management_views, aimodel_views, \
    sensor_views, weather_views, user_views, download_views

from main.views.annotation import model_annotation_views

urlpatterns = [
    path('', views.home_detail_view, name='index'),

    path('users/<int:user_pk>/update/',
         user_views.user_update_view,
         name='user-update'),

    path('management/',
         management_views.management_overview_view,
         name='management_overview'),
    path('management/tasks/',
         management_views.management_task_list_view,
         name='management-task-list'),
    path('management/ftp/change-admin-password',
         views.changeFTPAdminPassword,
         name='change-ftp-admin-password'),
    path('management/ftp/add-user',
         views.addFTPUser,
         name='add-ftp-user'),
    path('management/tasks/create/',
         management_views.task_create_view,
         name='task-create'),
    path('management/tasks/<int:task_pk>/',
         management_views.task_detail_view,
         name='task-detail'),
    path('management/tasks/<int:task_pk>/delete/',
         management_views.task_delete_view,
         name='task-delete'),
    path('management/hiveImages/',
         management_views.admin_hive_images_list_view,
         name='admin-hive-images-list'),
    path('management/hiveImages/select/',
         management_views.admin_hive_images_select_view,
         name='admin-hive-images-select'),
    path('environment/overview/',
         management_views.environment_overview_view,
         name='environment-overview'),
    path('apiary/overview/',
         management_views.apiary_overview_view,
         name='apiary-overview'),

    path('aimodels/',
         aimodel_views.aimodel_list_view,
         name='aimodel-list'),
    path('aimodels/upload/',
         aimodel_views.aimodel_upload_view,
         name='aimodel-upload'),
    path('machine_learning/validations/',
         aimodel_views.ml_validations_view,
         name='ml-validations'),
    path('aimodels/<int:aimodel_pk>/',
         aimodel_views.aimodel_detail_view,
         name='aimodel-detail'),

    path('validations/<int:hive_pk>/',
         aimodel_views.hive_validations_view,
         name='hive-validation-list'),

    path('validations/<int:aimodel_pk>/<int:hive_pk>/',
         aimodel_views.validation_detail_view,
         name='validation-detail'),
    path('machine_learning/overview/',
         aimodel_views.ml_overview_view,
         name='ml-overview'),
    path('machine_learning/data/',
         aimodel_views.ml_data_view,
         name='ml-data'
         ),
    path('machine_learning/annotation/',
         aimodel_views.ml_annotation_view,
         name='ml-annotation'),
    path('machine_learning/modelServingApp/',
         aimodel_views.ml_model_serving_app_view,
         name='ml-model-serving-app'),

    path('getretrainbeehives/',
         views.getRetrainBeehives,
         name='get-retrain-beehives'),
    path('registermodel/',
         views.registerNewModel,
         name='register-new-model'),

    path('tasks/',
         management_views.user_task_list_view,
         name='user-task-list'),

    # path('register/', views.register, name='register'),

    path('apiaries/create/', apiary_views.apiary_create_view,
         name='apiary-create'),
    path('apiaries/<int:pk>/', apiary_views.apiary_detail_view,
         name='apiary-detail'),
    path('apiaries/', apiary_views.apiary_list_view,
         name='apiary-list'),
    path('apiaries/<int:pk>/update/', apiary_views.apiary_update_view,
         name='apiary-update'),
    path('apiaries/<int:pk>/delete/', apiary_views.apiary_delete_view,
         name='apiary-delete'),

    path('apiaries/<int:pk>/addManager/', apiary_views.addManager,
         name='apiary-addManager'),
    path('apiaries/<int:apiary_pk>/deleteManager/<int:user_pk>',
         apiary_views.deleteManager,
         name='apiary-deleteManager'),

    path('apiaries/<int:pk>/addHive/', beehive_views.beehive_create_view,
         name='beehive-create'),

    path('apiaries/<int:pk>/weatherMeasurements/',
         weather_views.apiary_weather_measurement_list_view,
         name='apiary-weather-measurement-list'),

    path('apiaries/<int:pk>/weatherMeasurements/create/',
         weather_views.apiary_weather_measurement_create_view,
         name='apiary-weather-measurement-create'),

    path(
        'apiaries/<int:apiary_pk>/weatherMeasurements/<int:measurement_pk>/delete/',
        weather_views.weather_measurement_delete_view,
        name='apiary-weather-measurement-delete'),

    path('beehives/', beehive_views.beehive_list_view,
         name='beehive-list'),
    path('beehives/<int:beehive_pk>/similarBeehive/',
         beehive_views.select_similar_beehive_view,
         name='similar-beehive-select'),
    path('beehives/<int:pk>/', beehive_views.beehive_detail_view,
         name='beehive-detail'),
    path('beehives/<int:pk>/update/', beehive_views.beehive_update_view,
         name='beehive-update'),
    path('beehives/<int:pk>/delete/', beehive_views.beehive_delete_view,
         name='beehive-delete'),
    path('api/beehives/<int:hive_pk>/graphData/',
         beehive_views.beehive_graph_data_api_view,
         name='beehive-graph-data-api'),
    path('beehives/<int:beehive_pk>/images/',
         beehive_views.beehive_image_list_view,
         name='beehive-image-list'),
    path('beehives/<int:beehive_pk>/images/create/',
         beehive_views.beehive_image_create_view,
         name='beehive-image-create'),
    path('beehives/<int:beehive_pk>/videos/',
         beehive_views.beehive_video_list_view,
         name='beehive-video-list'),

    path('beehives/<int:pk>/addVideo/', video_views.video_create_view,
         name='video-create'),
    path('beehives/<int:pk>/generateSAS/', video_views.video_upload_sas_key,
         name='video-generatesas'),
    path('beehives/<int:pk>/confirmUpload/', video_views.confirmUpload,
         name='video-confirmupload'),
    path('api/beehives/confirmUploadFTP/', video_views.confirmUploadFTP,
         name='video-confirmuploadftp'),

    path('videos/', include('main.urls.video_urls')),

    path('frames/', frame_views.frame_list_view, name='frame-list'),
    path('frames/<int:pk>/', frame_views.frame_detail_view,
         name='frame-detail'),
    path('api/frames/<int:frame_pk>/',
         frame_views.api_frame_detail_view,
         name='frame-detail-api'),
    path('api/frames/<int:frame_pk>/path/',
         frame_views.frame_path_view,
         name='frame-path-api'),
    path('api/frames/',
         frame_views.api_frame_list_view,
         name='frame-list-api'),

    path('modelAnnotations/video/<int:video_pk>/check/',
         annotation_views.video_model_annotations_check,
         name='video-model-annotations'),
    path('modelAnnotations/video/<int:video_pk>/done/',
         annotation_views.video_model_annotations_check_done,
         name='video-model-annotations-done'),
    path('modelAnnotations/image/<int:image_pk>/check/',
         annotation_views.image_model_annotations_check,
         name='image-model-annotations'),
    path('api/modelAnnotations/<int:model_pk>/<int:frame_pk>/',
         annotation_views.model_annotation_list_api_view,
         name='frame-model-annotations-list-api'),
    path('api/modelAnnotations/create/',
         model_annotation_views.model_annotations_create_view,
         name='model-annotations-create-api'),

    path('api/userAnnotations/<int:user_pk>/<int:frame_pk>/',
         annotation_views.user_annotation_list_api_view,
         name='frame-user-annotations-list-api'),
    path('api/goldAnnotations/<int:frame_pk>/',
         annotation_views.gold_annotation_list_api_view,
         name='gold-annotations-list-api'),

    path('sensorTypes/create/',
         sensor_views.sensor_type_create_view,
         name='sensor-type-create'),
    path('sensorTypes/',
         sensor_views.sensor_type_list_view,
         name='sensor-type-list'),
    path('sensorTypes/<int:pk>/delete/',
         sensor_views.sensor_type_delete_view,
         name='sensor-type-delete'),
    path('sensorTypes/<int:pk>/update/',
         sensor_views.sensor_type_update_view,
         name='sensor-type-update'),

    path('beehives/<int:hive_pk>/addHiveSensorDevice/',
         sensor_views.hive_sensor_device_create_view,
         name='hive-sensor-device-create'),
    path('hiveSensorDevices/',
         sensor_views.hive_sensor_device_list_view,
         name='hive-sensor-device-list'),
    path('hiveSensorDevices/<int:device_pk>/',
         sensor_views.hive_sensor_device_detail,
         name='hive-sensor-device-detail'),
    path('hiveSensorDevices/<int:device_pk>/addSensor/',
         sensor_views.hive_sensor_create_view,
         name='hive-sensor-create'),
    path('hiveSensorDevices/<int:device_pk>/update/',
         sensor_views.hive_sensor_device_update_view,
         name='hive-sensor-device-update'),
    path('hiveSensorDevices/<int:device_pk>/bulkupload/',
         sensor_views.hive_sensor_device_bulk_upload,
         name='hive-sensor-device-bulk-upload'),
    path('api/hiveSensorDevices/<int:device_pk>/measurements/',
         sensor_views.hive_sensor_device_measurements_api_view,
         name='hive-sensor-device-measurements-api'),

    path('hiveSensors/<int:pk>/',
         sensor_views.hive_sensor_detail_view,
         name='hive-sensor-detail'),
    path('hiveSensors/<int:pk>/update/',
         sensor_views.hive_sensor_update_view,
         name='hive-sensor-update'),
    path('hiveSensors/<int:pk>/delete/',
         sensor_views.hive_sensor_delete_view,
         name='hive-sensor-delete'),
    path('hiveSensors/<int:sensor_pk>/addSensorMeasurement/',
         sensor_views.sensor_measurement_create_view,
         name='sensor-measurement-create'),

webApp/main/models/hive.py
from django.conf import settings
from django.db import models
from django.apps import apps

from main.models import Apiary
from main.models.machine_learning.model.validation import Validation


class Hive(models.Model):
    """Represents a beehive."""
    # To which apiary it belongs
    apiary = models.ForeignKey(Apiary, on_delete=models.CASCADE)
    # Who added the beehive
    creator = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                related_name="origin_owner_hive")
    # A human-readable name for the beehive (e.g. a number or a color)
    name = models.CharField(max_length=200)
    # Whether the data may be used for research purposes
    # TODO: move this up to the apiary level
    private = models.BooleanField(default=True)
    # original name on Google Drive
    google_drive_name = models.CharField(max_length=50, null=True, blank=True)
    # most similar beehive
    similar_beehive = models.ForeignKey('Hive', on_delete=models.SET_NULL,
                                        null=True, blank=True)

    # Whether a new model should be created
    retrain = models.BooleanField(default=False)

    # Shape of entrance
    class Entrance(models.TextChoices):
        CIRCULAR = 'circular'
        RECTANGULAR = 'rectangular'

    entrance = models.CharField(max_length=20, choices=Entrance.choices)

    class Meta:
        unique_together = ('apiary', 'name')

    def isManagedBy(self, user):
        return self.apiary.isManagedBy(user)

    @property
    def bee_model(self):
        """Get best bee model as determined by validation."""
        validations = Validation.objects\
            .filter(hive=self, model__annotation_type__name='bee')\
            .order_by('-f1')
        if validations:
            return validations.first().model

        return None

    @property
    def has_enough_hive_images(self):
        image_count = apps.get_model('main.Image').objects\
            .filter(image_set__video__beehive=self,
                    type=apps.get_model('main.Image').TYPE.HIVE)\
            .count()
        return image_count > 5

    @property
    def has_validation_images(self):
        validation_images = apps.get_model('main.Image').objects.filter(
            beehive=self,
            status=apps.get_model('main.Image').STATUS.VALIDATE)
        return len(validation_images) > 0

    @property
    def tasks(self):
        tasks = apps.get_model('main.HiveTask').objects.filter(hive=self)
        open_tasks = [task for task in tasks if not task.task.finished]
        return open_tasks

    @property
    def entrance_annotation(self):
        """The annotation of the hive entrance."""
        annotation_type = apps.get_model('main.AnnotationType').objects\
            .get(name='entrance')
        annotations = apps.get_model('main.GoldAnnotation').objects\
            .filter(annotation_set__image__beehive=self,
                    annotation_set__annotation_type=annotation_type)\
            .order_by('-pk')

        if annotations:
            return annotations.first()

        return None

    def __str__(self):
        return f'({self.apiary.name}) {self.name} - {self.pk}'

webApp/main/models/image_set.py
from django.db import models


class ImageSet(models.Model):
    path = models.CharField(max_length=255, unique=True, null=True)
    name = models.CharField(max_length=255)

    main_annotation_type = models.ForeignKey(
        to='main.AnnotationType',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        default=None
    )

    @property
    def first(self):
        """Get PK of first image in imageset."""
        first_image = self.images.order_by('frame').first().pk
        return first_image

    def isManagedBy(self, user):
        return self.video.isManagedBy(user)

webApp/main/views/download_views.py
from pathlib import Path

from django.shortcuts import render

from main.models import Image, GoldAnnotation
from main.util.azure_helpers import get_latest_snapshot_url


def download_list_view(request):
    return render(request, 'main/download/download_list.html', {})


def download_ml_data_view(request):
    total_image_count = Image.objects.filter(goldannotationset__isnull=False)\
        .distinct()\
        .count()

    bee_image_count = Image.objects\
        .filter(goldannotationset__annotation_type__name='bee')\
        .count()

    pollen_image_count = Image.objects\
        .filter(goldannotationset__annotation_type__name='pollen')\
        .count()

    bee_annotation_count = GoldAnnotation.objects\
        .filter(annotation_set__annotation_type__name='bee')\
        .count()

    pollen_annotation_count = GoldAnnotation.objects\
        .filter(annotation_set__annotation_type__name='pollen')\
        .count()

    base_url = 'https://beelivingsensor.blob.core.windows.net/public'

    latest_snapshot_url = get_latest_snapshot_url()
    if latest_snapshot_url:
        archive_name = Path(latest_snapshot_url).name
    else:
        archive_name = None

    context = {
        'tiny_pollen_model_url': f'{base_url}/models/pollen/pollen_tiny.weights',
        'large_pollen_model_url': f'{base_url}/models/pollen/pollen_large.weights',
        'medium_bee_model_url': f'{base_url}/models/bee/bee_medium.weights',
        'large_bee_model_url': f'{base_url}/models/bee/bee_large.weights',
        'latest_snapshot_url': latest_snapshot_url,
        'archive_name': archive_name,
        'total_image_count': total_image_count,
        'bee_image_count': bee_image_count,
        'pollen_image_count': pollen_image_count,
        'bee_annotation_count': bee_annotation_count,
        'pollen_annotation_count': pollen_annotation_count,
    }
    return render(request, 'main/download/download_ml_data.html', context)

webApp/main/views/user_views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect, render

from main.forms import UserForm
from main.models import User


@login_required
def user_update_view(request, user_pk):
    user = get_object_or_404(User, pk=user_pk)
    if request.user != user:
        raise PermissionDenied()

    user_form = UserForm(request.POST or None, instance=user)

    if user_form.is_valid():
        user_form.save()
        return redirect('index')

    context = {'user_form': user_form}

    return render(request, 'main/user/user_update.html', context)

webApp/main/templates/main/apiary/apiary_create.html
{% extends 'base/base.html' %}

{% block head %}
    {{ apiary_form.media }}
{% endblock %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'index' %}">
                    &lt;&lt;
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'index' %}">Home</a>
            </li>
            <li class="breadcrumb-item active">Add apiary</li>
        </ol>
    </nav>

    <h2 class="my-5">
        Add apiary
    </h2>

    <form method="post">{% csrf_token %}
        <table class="table">
            {{ apiary_form.as_table }}
        </table>
        <input class="btn btn-primary mt-4" type="submit" value="Save">
    </form>
{% endblock %}

webApp/main/templates/main/apiary/apiary_detail.html
{% extends 'base/base.html' %}
{% load l10n %}
{% load i18n %}

{% block head %}
    {% load leaflet_tags %}
    {% leaflet_css %}
    {% leaflet_js %}
{% endblock %}


{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'apiary-list' %}">
                    &lt;&lt;
                </a>
            </li>
            <li class="breadcrumb-item"><a href="{% url 'apiary-list' %}">Apiaries</a>
            </li>
            <li class="breadcrumb-item active">{{ apiary.name }}</li>
        </ol>
    </nav>

    <h1 class="my-5">{% trans 'Apiary' %} <span
            class="display-4 ml-5">{{ apiary.name }}</span></h1>

    <div class="row gy-2">

        <div class="col-xxl-6">

            <div class="d-flex justify-content-between">
                <h4 class="mb-5">{% trans 'Metadata' %}</h4>
                <a class="btn btn-primary mb-5"
                   href="{% url 'apiary-update' apiary.pk %}">
                    {% trans 'Edit' %}
                </a>
            </div>

            <table class="table table-hover table-responsive">
                <tbody>
                <tr>
                    <th scope="row">ID:</th>
                    <td>{{ apiary.pk }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans 'Creator' %}:</th>
                    <td>{{ apiary.creator }}</td>
                </tr>
                <tr>
                    <th scope="row">Name:</th>
                    <td>{{ apiary.name }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans 'Location' %}:</th>
                    <td>{{ apiary.location.y }}; {{ apiary.location.x }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans 'Address' %}:</th>
                    <td>{{ apiary.address }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans 'Elevation' %}:</th>
                    <td>{{ apiary.elevation }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans 'Managers' %}:</th>
                    <td>
                        <table class="table-borderless">
                            {% for manager in managers %}
                                <tr>
                                    <td>{{ manager.first_name }} {{ manager.last_name }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>

            <div class="row mt-5">
                <div class="col-xxl-12">
                    {% leaflet_map "main" callback="map_init" %}

                    <script type="text/javascript">
                        function map_init(map, options) {
                            const lon = "{{ apiary.location.x|unlocalize }}";
                            const lat = "{{ apiary.location.y|unlocalize }}";

                            // zoom to point & add it to map
                            map.setView([lat, lon], 15);
                            L.marker([lat, lon]).addTo(map);
                        }
                    </script>
                </div>
            </div>

            <div class="row mt-5">
                <div class="col-md-3">
                    <a class="btn btn-danger mb-5"
                       href="{% url 'apiary-delete' apiary.pk %}">
                        {% trans 'Delete apiary' %}
                    </a>
                </div>
            </div>


        </div>

        <div class="col-xxl-2"></div>

        <div class="col-xxl-4">
            <div class="d-flex justify-content-between">
                <h4 class="mb-3">{% trans 'Beehives' %}</h4>
                <a class="btn btn-primary mb-3"
                   href="{% url 'beehive-create' apiary.pk %}">
                    {% trans 'Add beehive' %}
                </a>
            </div>

            <table class="table mb-5">
                {% for hive in apiary.hive_set.all %}
                    {% url 'beehive-detail' hive.pk as hive_detail_url %}
                    <tr>
                        <td>#{{ hive.pk }}</td>
                        <td>{{ hive.name }}</td>
                        <td>
                            {% include 'base/show_button.html' with url=hive_detail_url %}
                        </td>
                    </tr>
                {% endfor %}
            </table>

            <hr class="mb-5">

            <div class="d-flex justify-content-between">
                <h4 class="mb-3">{% trans 'Weather data' %}</h4>
                <a class="btn btn-primary mb-3"
                   href="{% url 'apiary-weather-measurement-list' apiary.pk %}">
                    {% trans 'More' %}
                </a>
            </div>

            {% if weather_station %}
            <b>{{ weather_station.name }}
                ({{ weather_station.location.y }}, {{ weather_station.location.x }})</b>
            {% endif %}

            <table class="table mb-5 mt-3">
                {% for measurement in weather_measurements %}
                    <tr>
                        <td>{{ measurement.time }}</td>
                        <td>{{ measurement.parameter }}</td>
                        <td>{{ measurement.value }} {{ measurement.parameter.unit }}</td>
                    </tr>
                {% endfor %}
            </table>

        </div>
    </div>

{% endblock %}

webApp/main/templates/main/apiary/apiary_list.html
{% extends 'base/base.html' %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active">Apiaries</li>
        </ol>
    </nav>

    <h3 class="my-5">Apiaries</h3>

    {% include 'main/apiary/apiary_list_content.html' %}

{% endblock %}

webApp/main/templates/main/apiary/apiary_list_content.html
<div class="row">
    <div class="col-xxl-12 scrollbar">
        <table class="table">

            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Creator</th>
                <th scope="col">Name</th>
                <th scope="col">Hives</th>
                <th scope="col"></th>
            </tr>
            </thead>

            <tbody>
            {% for apiary in apiaries %}
                <tr>
                    <td>
                        {{ apiary.pk }}
                    </td>
                    <td>{{ apiary.creator }}</td>
                    <td>{{ apiary.name }}
                        {% url 'apiary-detail' apiary.pk as apiary_detail_url %}
                        {% include 'base/show_button.html' with url=apiary_detail_url %}
                    </td>
                    <td>
                        <table class="table">
                            <tbody>
                            {% for hive in apiary.hive_set.all %}
                                <tr>
                                    <td>
                                        {{ hive.name }}
                                        {% url 'beehive-detail' hive.pk as hive_detail_url %}
                                        {% include 'base/show_button.html' with url=hive_detail_url %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </td>
                    <td>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

webApp/main/templates/main/apiary/apiary_update.html
{% extends 'base/base.html' %}

{% block head %}
    {{ apiary_form.media }}
{% endblock %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'apiary-detail' apiary.pk %}">
                    &lt;&lt;
                </a>
            </li>
            <li class="breadcrumb-item"><a href="{% url 'apiary-list' %}">Apiaries</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'apiary-detail' apiary.pk %}">
                    {{ apiary.name }}
                </a>
            </li>
            <li class="breadcrumb-item active">Update</li>
        </ol>
    </nav>

    <h2 class="my-5">Update {{ apiary.name }}</h2>

    {% url 'apiary-detail' apiary.pk as apiary_detail_url %}
    {#    {% include 'base/back_button.html' with url=apiary_detail_url %}#}

    <form class="mb-5" method="post">{% csrf_token %}
        <table class="table">
            {{ apiary_form.as_table }}
        </table>
        <input class="btn btn-primary mt-4" type="submit" value="Update">
    </form>

    <hr>

    <div class="row mt-5">
        <div class="col-xxl-6">
            <h4>Add managers</h4>
            <form class="mb-5" method="post"
                  action="{% url 'apiary-addManager' apiary.pk %}">{% csrf_token %}
                <table class="table">
                    {{ add_manager_form.as_table }}
                </table>
                <input class="btn btn-primary mt-4" type="submit"
                       value="Add manger">
            </form>
        </div>
        <div class="col-xxl-6">
            <h4>Managers</h4>
            <table class="table">
                {% for manager in managers %}
                    <tr>
                        <td>{{ manager.first_name }} {{ manager.last_name }}: {{ manager.email }}</td>
                        <td>
                            <a href="{% url 'apiary-deleteManager' apiary.pk manager.pk %}">
                                <button class="btn btn-danger btn-sm">Remove
                                    manager
                                </button>
                            </a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

{% endblock %}