webApp/beewatch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.conf.urls.i18n import i18n_patterns
from django_registration.backends.one_step.views import RegistrationView
from main.forms import UserRegistrationForm

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('annotations/', include('main.urls.annotation_urls')),
    path('api/', include('main.urls.api.urls'))
]

urlpatterns += i18n_patterns(
    path('', include('main.urls.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('accounts/register/',
         RegistrationView.as_view(form_class=UserRegistrationForm),
         name='django_registration_register'),
    path('accounts/',
         include('django_registration.backends.activation.urls')),
    path('admin/', admin.site.urls),

    path('beefoodchecker/', include(
        'main.urls.environment.beefoodchecker_urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webApp/main/urls/api/urls.py
from django.urls import path, include

urlpatterns = [
    path('images/', include('main.urls.api.image_urls')),
    path('plants/', include('main.urls.api.plant_urls'))
]

webApp/main/urls/urls.py
from django.urls import path, include

from main.views import views, beehive_views, video_views, apiary_views, \
    frame_views, annotation_views, management_views, aimodel_views, \
    sensor_views, weather_views, user_views, download_views

from main.views.annotation import model_annotation_views

urlpatterns = [
    path('', views.home_detail_view, name='index'),

    path('users/<int:user_pk>/update/',
         user_views.user_update_view,
         name='user-update'),

    path('management/',
         management_views.management_overview_view,
         name='management_overview'),
    path('management/tasks/',
         management_views.management_task_list_view,
         name='management-task-list'),
    path('management/ftp/change-admin-password',
         views.changeFTPAdminPassword,
         name='change-ftp-admin-password'),
    path('management/ftp/add-user',
         views.addFTPUser,
         name='add-ftp-user'),
    path('management/tasks/create/',
         management_views.task_create_view,
         name='task-create'),
    path('management/tasks/<int:task_pk>/',
         management_views.task_detail_view,
         name='task-detail'),
    path('management/tasks/<int:task_pk>/delete/',
         management_views.task_delete_view,
         name='task-delete'),
    path('management/hiveImages/',
         management_views.admin_hive_images_list_view,
         name='admin-hive-images-list'),
    path('management/hiveImages/select/',
         management_views.admin_hive_images_select_view,
         name='admin-hive-images-select'),
    path('environment/overview/',
         management_views.environment_overview_view,
         name='environment-overview'),
    path('apiary/overview/',
         management_views.apiary_overview_view,
         name='apiary-overview'),

    path('aimodels/',
         aimodel_views.aimodel_list_view,
         name='aimodel-list'),
    path('aimodels/upload/',
         aimodel_views.aimodel_upload_view,
         name='aimodel-upload'),
    path('machine_learning/validations/',
         aimodel_views.ml_validations_view,
         name='ml-validations'),
    path('aimodels/<int:aimodel_pk>/',
         aimodel_views.aimodel_detail_view,
         name='aimodel-detail'),

    path('validations/<int:hive_pk>/',
         aimodel_views.hive_validations_view,
         name='hive-validation-list'),

    path('validations/<int:aimodel_pk>/<int:hive_pk>/',
         aimodel_views.validation_detail_view,
         name='validation-detail'),
    path('machine_learning/overview/',
         aimodel_views.ml_overview_view,
         name='ml-overview'),
    path('machine_learning/data/',
         aimodel_views.ml_data_view,
         name='ml-data'
         ),
    path('machine_learning/annotation/',
         aimodel_views.ml_annotation_view,
         name='ml-annotation'),
    path('machine_learning/modelServingApp/',
         aimodel_views.ml_model_serving_app_view,
         name='ml-model-serving-app'),

    path('getretrainbeehives/',
         views.getRetrainBeehives,
         name='get-retrain-beehives'),
    path('registermodel/',
         views.registerNewModel,
         name='register-new-model'),

    path('tasks/',
         management_views.user_task_list_view,
         name='user-task-list'),

    # path('register/', views.register, name='register'),

    path('apiaries/create/', apiary_views.apiary_create_view,
         name='apiary-create'),
    path('apiaries/<int:pk>/', apiary_views.apiary_detail_view,
         name='apiary-detail'),
    path('apiaries/', apiary_views.apiary_list_view,
         name='apiary-list'),
    path('apiaries/<int:pk>/update/', apiary_views.apiary_update_view,
         name='apiary-update'),
    path('apiaries/<int:pk>/delete/', apiary_views.apiary_delete_view,
         name='apiary-delete'),

    path('apiaries/<int:pk>/addManager/', apiary_views.addManager,
         name='apiary-addManager'),
    path('apiaries/<int:apiary_pk>/deleteManager/<int:user_pk>',
         apiary_views.deleteManager,
         name='apiary-deleteManager'),

    path('apiaries/<int:pk>/addHive/', beehive_views.beehive_create_view,
         name='beehive-create'),

    path('apiaries/<int:pk>/weatherMeasurements/',
         weather_views.apiary_weather_measurement_list_view,
         name='apiary-weather-measurement-list'),

    path('apiaries/<int:pk>/weatherMeasurements/create/',
         weather_views.apiary_weather_measurement_create_view,
         name='apiary-weather-measurement-create'),

    path(
        'apiaries/<int:apiary_pk>/weatherMeasurements/<int:measurement_pk>/delete/',
        weather_views.weather_measurement_delete_view,
        name='apiary-weather-measurement-delete'),

    path('beehives/', beehive_views.beehive_list_view,
         name='beehive-list'),
    path('beehives/<int:beehive_pk>/similarBeehive/',
         beehive_views.select_similar_beehive_view,
         name='similar-beehive-select'),
    path('beehives/<int:pk>/', beehive_views.beehive_detail_view,
         name='beehive-detail'),
    path('beehives/<int:pk>/update/', beehive_views.beehive_update_view,
         name='beehive-update'),
    path('beehives/<int:pk>/delete/', beehive_views.beehive_delete_view,
         name='beehive-delete'),
    path('api/beehives/<int:hive_pk>/graphData/',
         beehive_views.beehive_graph_data_api_view,
         name='beehive-graph-data-api'),
    path('beehives/<int:beehive_pk>/images/',
         beehive_views.beehive_image_list_view,
         name='beehive-image-list'),
    path('beehives/<int:beehive_pk>/images/create/',
         beehive_views.beehive_image_create_view,
         name='beehive-image-create'),
    path('beehives/<int:beehive_pk>/videos/',
         beehive_views.beehive_video_list_view,
         name='beehive-video-list'),

    path('beehives/<int:pk>/addVideo/', video_views.video_create_view,
         name='video-create'),
    path('beehives/<int:pk>/generateSAS/', video_views.video_upload_sas_key,
         name='video-generatesas'),
    path('beehives/<int:pk>/confirmUpload/', video_views.confirmUpload,
         name='video-confirmupload'),
    path('api/beehives/confirmUploadFTP/', video_views.confirmUploadFTP,
         name='video-confirmuploadftp'),

    path('videos/', include('main.urls.video_urls')),

    path('frames/', frame_views.frame_list_view, name='frame-list'),
    path('frames/<int:pk>/', frame_views.frame_detail_view,
         name='frame-detail'),
    path('api/frames/<int:frame_pk>/',
         frame_views.api_frame_detail_view,
         name='frame-detail-api'),
    path('api/frames/<int:frame_pk>/path/',
         frame_views.frame_path_view,
         name='frame-path-api'),
    path('api/frames/',
         frame_views.api_frame_list_view,
         name='frame-list-api'),

    path('modelAnnotations/video/<int:video_pk>/check/',
         annotation_views.video_model_annotations_check,
         name='video-model-annotations'),
    path('modelAnnotations/video/<int:video_pk>/done/',
         annotation_views.video_model_annotations_check_done,
         name='video-model-annotations-done'),
    path('modelAnnotations/image/<int:image_pk>/check/',
         annotation_views.image_model_annotations_check,
         name='image-model-annotations'),
    path('api/modelAnnotations/<int:model_pk>/<int:frame_pk>/',
         annotation_views.model_annotation_list_api_view,
         name='frame-model-annotations-list-api'),
    path('api/modelAnnotations/create/',
         model_annotation_views.model_annotations_create_view,
         name='model-annotations-create-api'),

    path('api/userAnnotations/<int:user_pk>/<int:frame_pk>/',
         annotation_views.user_annotation_list_api_view,
         name='frame-user-annotations-list-api'),
    path('api/goldAnnotations/<int:frame_pk>/',
         annotation_views.gold_annotation_list_api_view,
         name='gold-annotations-list-api'),

    path('sensorTypes/create/',
         sensor_views.sensor_type_create_view,
         name='sensor-type-create'),
    path('sensorTypes/',
         sensor_views.sensor_type_list_view,
         name='sensor-type-list'),
    path('sensorTypes/<int:pk>/delete/',
         sensor_views.sensor_type_delete_view,
         name='sensor-type-delete'),
    path('sensorTypes/<int:pk>/update/',
         sensor_views.sensor_type_update_view,
         name='sensor-type-update'),

    path('beehives/<int:hive_pk>/addHiveSensorDevice/',
         sensor_views.hive_sensor_device_create_view,
         name='hive-sensor-device-create'),
    path('hiveSensorDevices/',
         sensor_views.hive_sensor_device_list_view,
         name='hive-sensor-device-list'),
    path('hiveSensorDevices/<int:device_pk>/',
         sensor_views.hive_sensor_device_detail,
         name='hive-sensor-device-detail'),
    path('hiveSensorDevices/<int:device_pk>/addSensor/',
         sensor_views.hive_sensor_create_view,
         name='hive-sensor-create'),
    path('hiveSensorDevices/<int:device_pk>/update/',
         sensor_views.hive_sensor_device_update_view,
         name='hive-sensor-device-update'),
    path('hiveSensorDevices/<int:device_pk>/bulkupload/',
         sensor_views.hive_sensor_device_bulk_upload,
         name='hive-sensor-device-bulk-upload'),
    path('api/hiveSensorDevices/<int:device_pk>/measurements/',
         sensor_views.hive_sensor_device_measurements_api_view,
         name='hive-sensor-device-measurements-api'),

    path('hiveSensors/<int:pk>/',
         sensor_views.hive_sensor_detail_view,
         name='hive-sensor-detail'),
    path('hiveSensors/<int:pk>/update/',
         sensor_views.hive_sensor_update_view,
         name='hive-sensor-update'),
    path('hiveSensors/<int:pk>/delete/',
         sensor_views.hive_sensor_delete_view,
         name='hive-sensor-delete'),
    path('hiveSensors/<int:sensor_pk>/addSensorMeasurement/',
         sensor_views.sensor_measurement_create_view,
         name='sensor-measurement-create'),

webApp/main/views/environment/beefoodchecker/forms.py
from django.contrib.gis.forms import OSMWidget, PointField
from django.utils.translation import ugettext_lazy as _

from main.forms import BootstrapRawForm

from django import forms


class PlantFilterForm(BootstrapRawForm):

    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': _('Name'),
                'list': 'plantOptions'
            }
        ),
        required=False,
        label=_('Name')
    )


class PlantForm(BootstrapRawForm):

    street = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Glärnischstrasse 123'}),
        required=False
    )

    zip = forms.IntegerField(
        widget=forms.TextInput(attrs={'placeholder': '8750'}),
        required=False
    )

    city = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Glarus'}),
        required=False
    )

    radius = forms.IntegerField(
        widget=forms.TextInput(),
        initial=5,
        required=True
    )

    days = forms.IntegerField(
        widget=forms.TextInput(),
        initial=7,
        required=True
    )

    time = forms.DateTimeField(required=False)

    location = PointField(
        label="",
        srid=4326,
        widget=OSMWidget(attrs={
                'map_width': 1000,
                'map_height': 500,
                'default_lat': 46.7985,
                'default_lon': 8.2318,
                'default_zoom': 8
                }),
        required=False
    )

webApp/main/views/apiary_views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import permission_required, login_required

from main.forms import ApiaryForm, AddManagerApiaryForm
from main.models import Apiary, User, WeatherMeasurement
from main.decorators import user_is_manager

from geopy.geocoders import Nominatim

geolocator = Nominatim(user_agent="beewatch")


@permission_required('main.add_apiary')
def apiary_create_view(request):

    apiary_form = ApiaryForm(request.POST or None)

    if apiary_form.is_valid():
        apiary = apiary_form.save(commit=False)
        apiary.creator = request.user
        # prevent create tests from executing this
        if apiary.location:
            geo = geolocator.reverse(f"{apiary.location.y}, {apiary.location.x}")
            apiary.address = geo.address
        apiary.save()
        apiary.managers.add(request.user)
        return redirect('apiary-detail', pk=apiary.pk)

    context = {
        'apiary_form': apiary_form,
    }

    return render(request, 'main/apiary/apiary_create.html', context)

@permission_required('main.view_apiary')
@user_is_manager(Apiary)
def apiary_detail_view(request, pk):
    apiary = get_object_or_404(Apiary, pk=pk)
    managers = apiary.managers.all()

    weather_measurements = WeatherMeasurement.objects.filter(apiary=apiary).order_by('-time')[:4]
    weather_station = weather_measurements.first().weather_station if weather_measurements else ''

    context = {
        'weather_station': weather_station,
        'weather_measurements': weather_measurements,
        'apiary': apiary,
        "managers": managers
    }
    return render(request, 'main/apiary/apiary_detail.html', context)


@login_required
def apiary_list_view(request):
    apiaries = Apiary.objects.all()
    if not request.user.is_staff:
        apiaries = apiaries.filter(managers__pk=request.user.pk)

    context = {'apiaries': apiaries}
    return render(request, 'main/apiary/apiary_list.html', context)


@permission_required('main.change_apiary')
@user_is_manager(Apiary)
def apiary_update_view(request, pk):
    apiary = get_object_or_404(Apiary, pk=pk)
    apiary_form = ApiaryForm(request.POST or None, instance=apiary)
    addManagerForm = AddManagerApiaryForm()
    managers = apiary.managers.all()

    if apiary_form.is_valid():
        apiary = apiary_form.save(commit=False)
        if 'location' in apiary_form.changed_data:
            geo = geolocator.reverse(
                f"{apiary.location.y}, {apiary.location.x}")
            apiary.address = geo.address

        apiary.save()
        return redirect('apiary-detail', pk=pk)

    context = {
        'apiary_form': apiary_form,
        "add_manager_form": addManagerForm,
        "managers": managers,
        "apiary": apiary
    }
    return render(request, 'main/apiary/apiary_update.html', context)


@permission_required('main.delete_apiary')
@user_is_manager(Apiary)
def apiary_delete_view(_, pk):
    get_object_or_404(Apiary, pk=pk).delete()
    return redirect('apiary-list')


@permission_required('main.change_apiary')
@user_is_manager(Apiary)
def addManager(request, pk):
    managersForm = AddManagerApiaryForm(request.POST or None)
    if not managersForm.is_valid():
        return redirect('apiary-update', pk)
    email = managersForm.cleaned_data["email"]

    managers = User.objects.get(email=email)
    apiary = Apiary.objects.get(pk=pk)
    apiary.managers.add(managers)
    apiary.save()
    return redirect('apiary-update', pk)


@permission_required('main.change_apiary')
@user_is_manager(Apiary, "apiary_pk")
def deleteManager(request, apiary_pk, user_pk):
    manager = User.objects.get(pk=user_pk)
    apiary = Apiary.objects.get(pk=apiary_pk)
    if apiary.creator == manager:
        redirect('apiary-update', apiary_pk)
        print("Cannot remove creator from the managers!") # Allowing the removal of the creator could create "memory" leaks in the DB, i.e. there would be objects that nobody has access to.
    apiary.managers.remove(manager)
    apiary.save()
    return redirect('apiary-update', apiary_pk)

webApp/main/views/user_views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect, render

from main.forms import UserForm
from main.models import User


@login_required
def user_update_view(request, user_pk):
    user = get_object_or_404(User, pk=user_pk)
    if request.user != user:
        raise PermissionDenied()

    user_form = UserForm(request.POST or None, instance=user)

    if user_form.is_valid():
        user_form.save()
        return redirect('index')

    context = {'user_form': user_form}

    return render(request, 'main/user/user_update.html', context)

webApp/main/templates/main/sensor/hive_sensor_bulk_upload.html
{% extends 'base/base.html' %}

{% block content %}

    <div class="row">
        <div class="col-6">
            <h3 class="mb-5">Upload sensor data</h3>

            <form method="post" enctype="multipart/form-data">{% csrf_token %}
                <table class="table table-responsive">
                    <tbody>
                    {{ upload_form.as_table }}
                    </tbody>
                </table>
                <input class="btn btn-primary" type="submit"
                       value="Upload">
            </form>
        </div>
    </div>
{% endblock %}

webApp/main/templates/main/sensor/hive_sensor_create.html
{% extends 'base/base.html' %}

{% block head %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-6">
            <h3 class="mb-5">{{ title|default:"Create hive sensor" }}</h3>

            <form method="post">{% csrf_token %}
                <table class="table table-responsive">
                    <tbody>
                    {{ hive_sensor_form.as_table }}
                    </tbody>
                </table>
                <input class="btn btn-primary" type="submit"
                       value="{{ submit|default:"Create hive sensor" }}">
            </form>
        </div>
    </div>

    <script>
        // date/time picker for valid from/until
        flatpickr("#id_valid_from", {enableTime: true, dateFormat: "Y-m-d H:i",});
        flatpickr("#id_valid_until", {enableTime: true, dateFormat: "Y-m-d H:i",});
    </script>

{% endblock %}

webApp/main/templates/main/sensor/hive_sensor_detail.html
{% extends 'base/base.html' %}
{% load static %}

{% block head %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/5.16.0/d3.min.js"
            integrity="sha512-FHsFVKQ/T1KWJDGSbrUhTJyS1ph3eRrxI228ND0EGaEp6v4a/vGwPWd3Dtd/+9cI7ccofZvl/wulICEurHN1pg=="
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/graph.css' %}">
{% endblock %}

{% block content %}
    {% url 'hive-sensor-device-detail' hive_sensor.device.pk as hive_sensor_device_detail_url %}
    {% include 'base/back_button.html' with url=hive_sensor_device_detail_url %}

    <div class="row g-5 mb-5">
        <div class="col-xxl-7">
            <div class="d-flex justify-content-between">
                <h3 class="mb-5">Hive Sensor #{{ hive_sensor.pk }}</h3>
                <div>
                    <a href="{% url 'hive-sensor-delete' hive_sensor.pk %}"
                       class="btn btn-danger">
                        Delete sensor
                    </a>
                </div>
                <div>
                    <a href="{% url 'hive-sensor-update' hive_sensor.pk %}"
                       class="btn btn-primary">
                        Edit
                    </a>
                </div>
            </div>

            <table class="table table-responsive mb-5">
                <tr>
                    <th>Hive:</th>
                    <td>
                        <a href="{% url 'beehive-detail' hive_sensor.device.hive.pk %}">
                            {{ hive_sensor.device.hive.name }}
                        </a>
                    </td>
                </tr>
                <tr>
                    <th>Device:</th>
                    <td>
                        <a href="{% url 'hive-sensor-device-detail' hive_sensor.device.pk %}">
                            {{ hive_sensor.device.brand }}: {{ hive_sensor.device.model }}
                        </a>
                    </td>
                </tr>
                <tr>
                    <th>Sensor type:</th>
                    <td>{{ hive_sensor.sensor_type.name }}</td>
                </tr>
                <tr>
                    <th>Description:</th>
                    <td>{{ hive_sensor.description }}</td>
                </tr>
                <tr>
                    <th>Valid from:</th>
                    <td>{{ hive_sensor.valid_from|default_if_none:"infinity" }}</td>
                </tr>
                <tr>
                    <th>Valid until:</th>
                    <td>{{ hive_sensor.valid_until|default_if_none:"infinity" }}</td>
                </tr>
            </table>

            {% url 'hive-sensor-measurements-api' pk=hive_sensor.pk as sensor_measurements_url %}
            {% include 'main/sensor/sensor_multiline_chart.html' with url=sensor_measurements_url %}
        </div>

        <div class="col-xxl-1"></div>

        <div class="col-xxl-4">
            <div class="d-flex justify-content-between">
                <h3 class="mb-5">Measurement</h3>
                <div>
                    <a href="{% url 'sensor-measurement-create' hive_sensor.pk %}"
                       class="btn btn-primary">
                        Add measurement
                    </a>
                </div>
            </div>

            <table class="table table-hover table-responsive">
                <thead>
                <tr>
                    <th>Time</th>
                    <th>Value</th>
                </tr>
                </thead>
                <tbody>
                {% for measurement in sensor_measurements %}
                    <tr>
                        <td>{{ measurement.time }}</td>
                        <td>{{ measurement.value }} {{ measurement.sensor.sensor_type.unit }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

webApp/main/templates/main/sensor/hive_sensor_update.html
{% include 'main/sensor/hive_sensor_create.html' with title="Edit hive sensor" submit="Update hive sensor" %}

webApp/main/templates/main/sensor/sensor_device_create.html
{% extends 'base/base.html' %}

{% block content %}

    <div class="row">
        <div class="col-6">
            <h3 class="mb-5">{{ title|default:"Create hive sensor device" }}</h3>

            <form method="post">{% csrf_token %}
                <table class="table table-responsive">
                    <tbody>
                    {{ hive_sensor_device_form.as_table }}
                    </tbody>
                </table>
                <input class="btn btn-primary" type="submit"
                       value="{{ submit|default:"Create hive sensor device" }}">
            </form>
        </div>
    </div>

    <script>
        // brand selection
        let brand_input = document.getElementById('id_brand');
        let brand_row = brand_input.parentElement.parentElement
        brand_row.setAttribute('hidden', true);

        const selectElement = document.getElementById('id_brand_choices');

        if (selectElement.selectedOptions[0].value === 'custom'){
            brand_row.removeAttribute('hidden');
        }

        selectElement.addEventListener('change', (event) => {
            let selectedBrand = event.target.value;
            if (selectedBrand === 'custom') {
                brand_input.setAttribute('value', '');
                brand_row.removeAttribute('hidden');
            }
            else {
                brand_row.setAttribute('hidden', true);
                brand_input.setAttribute('value', '');
            }
        });
    </script>

{% endblock %}

webApp/main/templates/main/sensor/sensor_device_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    {% url 'beehive-detail' hive.pk as hive_detail_url %}
    {% include 'base/back_button.html' with url=hive_detail_url %}

    <div class="row mb-5">
        <div class="col-6 d-flex justify-content-between">
            <h3>Sensor devices for hive {{ hive.name }}</h3>
            <div>
                <a class="btn btn-primary float-right"
                   href="{% url 'hive-sensor-device-create' hive.pk %}">
                    Add sensor device
                </a>
            </div>
        </div>
    </div>

    <div class="row mb-5">
        <div class="col-6">
            <table class="table table-responsive table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Serial Number</th>
                    <th>Brand</th>
                    <th>Model</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for device in hive_sensor_devices %}
                    <tr>
                        <td>{{ device.pk }}</td>
                        <td>{{ device.sn }}</td>
                        <td>{{ device.brand }}</td>
                        <td>{{ device.model }}</td>
                        <td>
                            {% url 'hive-sensor-device-detail' device.pk as device_detail_url %}
                            {% include 'base/show_button.html' with url=device_detail_url %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

webApp/main/templates/main/sensor/sensor_device_update.html
{% include 'main/sensor/sensor_device_create.html' with title="Update hive sensor device" submit="Update" %}

webApp/main/templates/main/sensor/sensor_measurement_create.html
{% extends 'base/base.html' %}

{% block head %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
{% endblock %}

{% block content %}
    {% url 'hive-sensor-detail' sensor.pk as sensor_detail_url %}
    {% include 'base/back_button.html' with url=sensor_detail_url %}

    <div class="row">

        <div class="col-xl-6">
            <h3 class="mb-5">Add measurement for sensor</h3>

            <table class="table table-responsive table-hover mb-5">
                <tbody>
                    <tr>
                        <th>Brand</th>
                        <td>{{ sensor.device.brand }}</td>
                    </tr>
                    <tr>
                        <th>Model</th>
                        <td>{{ sensor.device.model }}</td>
                    </tr>
                    <tr>
                        <th>Parameter</th>
                        <td>{{ sensor.sensor_type.name }} in {{ sensor.sensor_type.unit }}</td>
                    </tr>
                </tbody>
            </table>

            <form method="post">{% csrf_token %}
                <table class="table table-responsive">
                    {{ sensor_measurement_form.as_table }}
                </table>
                <input class="btn btn-primary" type="submit"
                       value="Add">
            </form>
        </div>
    </div>

    <script>
        flatpickr("#id_time", {enableTime: true, dateFormat: "Y-m-d H:i",});
    </script>

{% endblock %}

webApp/main/templates/main/sensor/sensor_type_create.html
{% extends 'base/base.html' %}

{% block content %}
    <h3 class="mb-5">Create sensor type</h3>

    <form method="post">{% csrf_token %}
        <table class="table table-responsive">
            <tbody>
            {{ sensor_type_form.as_table }}
            </tbody>
        </table>
        <input class="btn btn-primary" type="submit"
               value="Create sensor type">
    </form>
{% endblock %}

webApp/main/templates/main/sensor/sensor_type_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'environment-overview' %}">
                    &lt;&lt;
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'management_overview' %}">
                    Admin
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'environment-overview' %}">
                    Environment
                </a>
            </li>
            <li class="breadcrumb-item active">Sensors</li>
        </ol>
    </nav>

    <div class="row my-5">
        <div class="col-6 d-flex justify-content-between">
            <h3>Sensor Types</h3>
            <div>
                <a class="btn btn-primary float-right"
                   href="{% url 'sensor-type-create' %}">
                    Create sensor type
                </a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-6">
            <table class="table table-responsive">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Unit</th>
                    <th>Description</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for sensor_type in sensor_types %}
                    <tr>
                        <td>{{ sensor_type.pk }}</td>
                        <td>{{ sensor_type.name }}</td>
                        <td>{{ sensor_type.unit }}</td>
                        <td>{{ sensor_type.description }}</td>
                        <td>
                            {% url 'sensor-type-update' sensor_type.pk as sensor_type_update_url%}
                            {% include 'base/sm_edit_button.html' with url=sensor_type_update_url %}
                        </td>
                        <td>
                            {% url 'sensor-type-delete' sensor_type.pk as sensor_type_delete_url %}
                            {% include 'base/sm_delete_button.html' with url=sensor_type_delete_url %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>


{% endblock %}